name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Fetch Upstream
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git remote add upstream https://github.com/nf-core/scrnaseq.git
        git fetch upstream
        git checkout master
        git merge upstream/master
        git push
